name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Set up environment variables
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "JWT_SECRET=test-secret" >> $GITHUB_ENV
          echo "STORAGE_TYPE=local" >> $GITHUB_ENV
          echo "LOCAL_STORAGE_PATH=uploads" >> $GITHUB_ENV

      - name: Lint
        run: npm run lint

      - name: Run Jest tests
        run: npm test
        env:
          CI: true
          DB_PATH: memories.db

      - name: Build
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          CI: true
          DB_PATH: memories.db

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            playwright-report/
            coverage/
          retention-days: 30

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build frontend
        run: npm run build
